version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://backend:5000  
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - FRONTEND_URL=frontend
      - DB_USER=postgres
      - DB_PASSWORD=reddy1406
      - DB_HOST=postgres-db  
      - DB_NAME=SkillSage
      - DB_PORT=5432
      - OPEN_AI_SECRET=
      - GROQ_API_KEY=
      - COOKIE_NAME=auth_token
      - COOKIE_SECRET=kqfjeiwfhoiehgeihg
      - JWT_SECRET=qwifhouqf2r013u823yr32
      - O1_KEY0=
      - O1_KEY=
    volumes:
      - ./backend:/app
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=reddy1406
      - POSTGRES_DB=SkillSage
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
